apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

apiVersion: v1
kind: ConfigMap
metadata:
  name: guestbook-cm
data:
  API_URL: "http://google.fr"

patches:
  - path: minimum-replicas.yaml
    target:
      kind: Deployment